repository:
  name: repository-settings
  description: Pull Requests for GitHub repository settings
  homepage: https://github.com/akinahmet/repository-settings
  topics: probot-app, github-app
  private: false
  has_wiki: false
  default_branch: main